### ISSUE TITLE
chrome打开百度云没有PD的下载按钮

### ISSUE THREAD

**Issue by kettly1260** [proxyee-down-org/proxyee-down#1114] opened 2018-11-23 10:32 UTC

**Comment by monkeyWie** [comment] 2018-11-29 02:53
换别的浏览器呢？

**Comment by bfx1000** [comment] 2018-11-29 09:33
Duplicate of #1125 或者试试这个
![image](https://user-images.githubusercontent.com/23432704/49212362-d1aec480-f3fc-11e8-9971-d1c7cfcc4198.png)

**Closed** 2018-11-30 01:18 UTC
